# -*- coding: utf-8 -*-
"""UTS_2306053_Muhammad Rizki Purnama A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iwHQLDZuWFKTZbjQet29sy7tUPM9SIfR
"""

# Sistem Pakar Deteksi Hama Tanaman

# Daftar aturan gejala dan kemungkinan hama
aturan_hama = {
    "daun menguning": "Tungau",
    "bercak hitam": "Jamur Cercospora",
    "daun berlubang": "Kumbang Daun",
    "tanaman layu": "Rhizoctonia"
}

# Fungsi untuk mendeteksi hama berdasarkan gejala
def deteksi_hama(gejala_list):
    hasil = []
    for gejala in gejala_list:
        hama = aturan_hama.get(gejala.lower())
        if hama:
            hasil.append(f"Gejala '{gejala}' mengindikasikan kemungkinan terkena {hama}.")
        else:
            hasil.append(f"Gejala '{gejala}' tidak dikenali dalam sistem.")
    return hasil

# User Interface
print("=== Sistem Pakar Deteksi Hama Tanaman ===")
print("Masukkan gejala tanaman yang dialami.")
print("Contoh input: daun menguning, bercak hitam")

input_gejala = input("Masukkan gejala (pisahkan dengan koma): ")
list_gejala = [g.strip() for g in input_gejala.split(',')]

# Proses deteksi
hasil_deteksi = deteksi_hama(list_gejala)

# Tampilkan hasil
print("\nHasil Deteksi:")
for hasil in hasil_deteksi:
    print("-", hasil)